[programs.localnet]
anchor_practice = "Ea2Y84kPvX59KwcEAs8VrbDASVacRo3N2CpkuryzWHq6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jeff0723/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
